config/routes.rb
Rails.application.routes.draw do

  resources :departments
	resources :products, only: [:new, :create, :destroy, :edit, :update] 
	get "/products/search" => "products#search", as: :search_product
  root "products#index" 

end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :department
	
	validates :name, length: { 	minimum: 5 }
	validates :amount, presence: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/1
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to @department, notice: 'Department was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      redirect_to @department, notice: 'Department was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    redirect_to departments_url, notice: 'Department was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def department_params
      params.require(:department).permit(:name, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:edit, :update, :destroy]
	
	def index 
		@products = Product.order('id DESC').limit 50
	end

	def search
		@name_search = params[:name]
		@products_search = Product.where "name like ?", "%#{@name_search}%"
	end
	
	def new
		@product = Product.new
		rendering :new
	end

	def create
		@product = Product.new product_params
		if @product.save
			flash[:notice] = "Successfully saved product"		 
			redirect_to root_path
		else
			rendering :new
		end
	end
	
	def edit		
		rendering :edit
	end

	def update			
		if @product.update product_params 
			flash[:notice] = "Successfully upgraded product"
			redirect_to root_path
		else
			rendering :edit
		end
	end

	def destroy			
		@product.destroy
		redirect_to root_url
	end

	private 

	def set_product
		@product = Product.find(params[:id])
	end

	def rendering(view)
		@departments = Department.all.order('name ASC')
		render view
	end

	def product_params
		params.require(:product)
			.permit :name, :description, :price, :amount, :department_id			
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.description %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @department.description %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartbodystore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= nav_bar brand: "SmartBody Store", brand_link: root_path  do %>
		<%= form_tag search_product_path, method: :get,
								 class: "navbar-form navbar-right" do %>
			<div class="form-group">
				<%= text_field_tag :name, @name_search,
											     class: "form-control" %>
				<%= button_to "Search", nil, class: "btn btn-default" %>
			</div>	
		<% end %>
	<% end %> 
	<div class="container">		
		<%= yield %>
	</div>
</body>
</html> 

app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role="alert">
		<%= message %>
	</div>
<% end %>

<div class="container form-horizontal" style="width:50%; margin-top:20px;">		
	<h1 style="text-align:center">Form Register</h1>
	<%= form_for @product do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name,
				class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, rows: 4,
				class: "form-control" %> 
		</div>

		<div class="form-group">
			<%= f.label :department %>
			<%= f.collection_select :department_id, @departments, :id, :name,
				{}, class: "form-control" %>
		</div>

		<div class="form-inline">
			<div class="form-group" style="width: 50%;">
				<%= f.label :price %>
				<%= f.number_field :price, step: 0.01,
					class: "form-control" %>
			</div>
			<div class="form-group" style="width: 50%;">
				<%= f.label :amount %>
				<%= f.number_field :amount, step: 1,
					class: "form-control" %>
			</div>
		</div>
		
		<div class="form-group" style="margin-top:20px">
			<%=  f.submit button_value, class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

app/views/products/_product.html.erb
<tr>
	<th><%= product.name %></th>
	<th><%= product.description %></th>
	<th><%= product.price %></th>
	<th>
		<%=
			button_to "Remove", product,
				class: "btn btn-danger",
					method: :delete,
						data: { confirm: "Do you want to delete #{product.name} ?" }
		%>
	</th>
	<th>
		<%= 
			link_to "Update", edit_product_path(product),
				class: 'btn btn-default'
		%>
	</th>		

</tr>

app/views/products/edit.html.erb
<%= render partial: 'form', locals: { button_value: 'Update' } %>

app/views/products/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice] %>
	</div>
<% end %>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Price</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>			
		<%= render @products %>		
	</tbody>
</table>

<%= link_to "Add Product", new_product_path %>

app/views/products/new.html.erb
<%= render partial: 'form', locals: { button_value: 'Create' } %>

app/views/products/search.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Price</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>			
		<%= render @products_search %>		 
	</tbody>
</table>

<%= link_to "Add Product", new_product_path %>